### ISSUE TITLE
Exception in IS-05 test 31

### ISSUE THREAD

**Issue by btrost-harmonicinc** [RiedelCommunications/test-nmos-is0405#4]
See the walkback below. Test 32 has a similar exception.

Thanks,
Bill

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sable/bt/git/test-nmos-is0405/nmos-test.py", line 57, in index_page
    result = test_obj.run_tests()
  File "/home/sable/bt/git/test-nmos-is0405/IS0501Test.py", line 117, in run_tests
    self.result.append(self.test_31())
  File "/home/sable/bt/git/test-nmos-is0405/IS0501Test.py", line 738, in test_31
    valid, response = self.compare_to_schema("v1.0-sender-response-schema.json", activeUrl)
  File "/home/sable/bt/git/test-nmos-is0405/IS0501Test.py", line 1559, in compare_to_schema
    Draft4Validator(schema, resolver=resolver).validate(response)
  File "/usr/lib/python2.7/dist-packages/jsonschema/validators.py", line 122, in validate
    for error in self.iter_errors(*args, **kwargs):
  File "/usr/lib/python2.7/dist-packages/jsonschema/validators.py", line 98, in iter_errors
    for error in errors:
  File "/usr/lib/python2.7/dist-packages/jsonschema/_validators.py", line 291, in properties_draft4
    schema_path=property,
  File "/usr/lib/python2.7/dist-packages/jsonschema/validators.py", line 114, in descend
    for error in self.iter_errors(instance, schema):
  File "/usr/lib/python2.7/dist-packages/jsonschema/validators.py", line 98, in iter_errors
    for error in errors:
  File "/usr/lib/python2.7/dist-packages/jsonschema/_validators.py", line 328, in oneOf_draft4
    errs = list(validator.descend(instance, subschema, schema_path=index))
  File "/usr/lib/python2.7/dist-packages/jsonschema/validators.py", line 114, in descend
    for error in self.iter_errors(instance, schema):
  File "/usr/lib/python2.7/dist-packages/jsonschema/validators.py", line 98, in iter_errors
    for error in errors:
  File "/usr/lib/python2.7/dist-packages/jsonschema/_validators.py", line 199, in ref
    scope, resolved = validator.resolver.resolve(ref)
  File "/usr/lib/python2.7/dist-packages/jsonschema/validators.py", line 336, in resolve
    return url, self._remote_cache(url)
  File "/usr/lib/python2.7/dist-packages/functools32/functools32.py", line 400, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/jsonschema/validators.py", line 346, in resolve_from_url
    raise RefResolutionError(exc)
RefResolutionError: <urlopen error file not on local host>
```

**Comment by billt-hlit** [comment]
Never mind, I accidentally ran it using python 2.7. It might be nice if the test program were to check it were running under python 3, though.
