### ISSUE TITLE
Exception is IS-06 tests

### ISSUE THREAD

**Issue by SoloAs** [RiedelCommunications/test-nmos-is0405#9]
Hi, Alexander Tyutyarev from Macnica here!
As soon as I'm trying run tests after pointing them to Network Controller, I'm getting this:

> 127.0.0.1 - - [09/Nov/2018 17:32:39] "POST / HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "/home/alex/work/autotests/nmos-testing/flask_test_app/.env/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "/home/alex/work/autotests/nmos-testing/flask_test_app/.env/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "/home/alex/work/autotests/nmos-testing/flask_test_app/.env/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/alex/work/autotests/nmos-testing/flask_test_app/.env/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/alex/work/autotests/nmos-testing/flask_test_app/.env/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/alex/work/autotests/nmos-testing/flask_test_app/.env/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/alex/work/autotests/nmos-testing/flask_test_app/.env/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/alex/work/autotests/nmos-testing/flask_test_app/.env/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/alex/work/autotests/nmos-testing/nmos-test.py", line 146, in index_page
>     test_obj = IS0601Test.IS0601Test(apis, spec_versions, version, spec_path)
>   File "/home/alex/work/autotests/nmos-testing/IS0601Test.py", line 23, in __init__
>     GenericTest.__init__(self, apis, spec_versions, test_version, spec_path)
>   File "/home/alex/work/autotests/nmos-testing/GenericTest.py", line 68, in __init__
>     raise Exception("No branch matching the expected patterns was found in the Git repository")
> Exception: No branch matching the expected patterns was found in the Git repository

I did a little debugging, and found the issue: 
While IS-06 got this repo: 

> <git.Repo "/home/alex/work/autotests/nmos-testing/cache/is-06/.git">

With following branches:

>   (HEAD detached at origin/master)
>   master
>   remotes/origin/HEAD -> origin/master
>   remotes/origin/gh-pages
>   remotes/origin/master

Source code is still looking for branch names with something like " *.x" in it (like it is in IS-04/05 tests) thus getting the previous exception. 

I've implemented temporary solution for this by switching to master branch in case we stumble upon IS-06 tests:

> repoPath = repo.git.rev_parse("--show-toplevel")
>  if "is-06" in repoPath:
>             spec_branch = "remotes/origin/master"

 But I think that would be better to add needed branches to repository.

Thanks in advance
Alexander

**Comment by andrewbonney** [comment]
Hi Alexander. Yes, we're hoping all specs will soon conform to using branches like 'v1.0.x' and 'v1.1-dev' which ensures the test suite is compatible. I believe Pete queried this on the IS-06 Basecamp but as yet the repository hasn't been updated.
